nelmio_cors:
    defaults:
        origin_regex: true
        # allow_origin: ['http://graindevrac.mathieuchamoulaud.com', 'http://localhost:3000/']
        allow_origin: ['*']
        allow_methods: ['GET', 'POST']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
